ALLOWED_FIELDS = {
    "id",
    "nota_fiscal",
    "emissao",
    "produto_id",
    "descricao",
    "marca",
    "tipo_estoque",
    "cliente",
    "uf",
    "cidade",
    "quantidade",
    "preco_cheio",
    "preco_unitario",
    "faturamento",
    "cmv",
    "mc",
    "mc_percentual",
    "frete",
    "comissao",
    "icms",
    "pis",
    "cofins",
    "tipo_frete",
    "created_at",
    "custo_reposicao",
}

FIELD_ALIASES = {
    "produto_nome": "descricao",
    "produto": "produto_id",
    "nome_produto": "descricao",
    "desc_produto": "descricao",
    "nota": "nota_fiscal",
    "estado": "uf",
}
